version: '3.9'

volumes:
  db:

services:
  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT}:5432'

  db_manager:
    image: adminer:4-standalone
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    depends_on:
      - database
    ports:
      - '${DATABASE_MANAGER_PORT}:8080'
