version: '3.9'

volumes:
  db:
  redis:

services:
  server:
    build: .
    image: oratorij/backend
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      CORS_ORIGIN: ${CORS_ORIGIN}
      SESSION_SECRET: ${SESSION_SECRET}
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      REDIS_URL: redis:${REDIS_PORT}
    depends_on:
      - database
      - redis
    ports:
      - '${PORT}:4000'

  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${DATABASE_NAME},${DATABASE_NAME}_test
    volumes:
      - db:/var/lib/postgresql/data
      - ./pg-init:/docker-entrypoint-initdb.d
    ports:
      - '${DATABASE_PORT}:5432'

  redis:
    image: redis:6.2.4-alpine
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis:/var/lib/redis

  db_manager:
    image: adminer:4-standalone
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    depends_on:
      - database
    ports:
      - '${DATABASE_MANAGER_PORT}:8080'
